Repository spidernet-io/egressgateway, pull requests merged in 2023-09, with the labels that each got.

#731 e2e: update install calico
  .github/workflows/call-e2e.yaml
  Makefile.defs
  test/Makefile
  test/scripts/installCalico.sh
  test/scripts/installE2eTools.sh
Labels: release/none

#754 [test-debug] pending test case EgressPolicy
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#747 Update uninstall process
  charts/README.md
  charts/templates/deleteHook.yaml
  charts/templates/role.yaml
  charts/values.yaml
  cmd/controller/cmd/clean.go
  cmd/controller/cmd/root.go
  pkg/k8s/apis/v1beta1/rbac.go
Labels: release/feature-new

#755 [docs]: optimize doc version for egressgateway
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-pages.yaml
Labels: documentation, release/feature-changed

#762 Adjust directory structure
  charts/egressgateway-0.1.0-rc0.tgz
  charts/egressgateway-0.1.0.tgz
  charts/egressgateway-0.2.0-rc0.tgz
  charts/egressgateway-0.2.0-rc1.tgz
  charts/egressgateway-0.2.0-rc2.tgz
  charts/egressgateway-0.2.0.tgz
  index.yaml
Labels: release/feature-changed

#763 Decoupling chart and website
  .github/workflows/auto-release.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-pages.yaml
Labels: release/feature-changed

#769 underlay CNI supports desgin
  docs/proposal/06-underlay-cni-supports/README_zh-CN.md
  docs/proposal/06-underlay-cni-supports/underlay_datapath.png
  docs/proposal/06-underlay-cni-supports/underlay_error_reply_datapath.png
  docs/proposal/06-underlay-cni-supports/underlay_reply_datapath.png
  docs/proposal/06-underlay-cni-supports/underlay_send_datapath.png
Labels: documentation, release/feature-new

#775 Fix json type
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  pkg/k8s/apis/v1beta1/egressgateway_types.go
Labels: release/bug

#782 fix failed update egci status
  pkg/controller/egress_cluster_info/egress_cluster_info.go
Labels: release/none

#768 cancel get egci when update
  pkg/controller/egress_cluster_info/egress_cluster_info.go
Labels: release/none
