Repository spidernet-io/egressgateway, pull requests merged in 2023-04, with the labels that each got.

#271 opened some pending cases about egressgateway and egressnode
  test/e2e/common/egressgateway.go
  test/e2e/common/egressnode.go
  test/e2e/common/node.go
  test/e2e/egressgateway/egressgateway_suite_test.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egressnode/egressnode_suite_test.go
  test/e2e/egressnode/egressnode_test.go
Labels: release/none

#283 roadmap
  docs/develop/roadmap.md
Labels: release/none

#285 update document
  docs/proposal/03-egress-ip/README_zh-CN.md
Labels: documentation, release/none

#286 Add proposal of auto detect egress ignore CIDR
  docs/proposal/04-auto-detect-egress-ignore-cidr/README_zh-CN.md
Labels: release/feature

#284 Add mark allocator
  pkg/markallocator/allocator.go
Labels: release/feature

#293 Fix the scope of crd
  charts/crds/egressgateway.spidernet.io_egressendpointslices.yaml
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressendpointslice_types.go
Labels: release/none

#295 update EgressGateway CRD
  docs/proposal/03-egress-ip/README_zh-CN.md
Labels: documentation, release/none

#297 update EgressGateway CRD
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  docs/proposal/03-egress-ip/README_zh-CN.md
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressgateway_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/zz_generated.deepcopy.go
Labels: release/none

#300 New EgressGatewayPolicyCluster proposal
  docs/proposal/05-egress-gateway-policy-cluster/README_zh-CN.md
Labels: release/feature

#287 pending e2e case
  .github/workflows/call-e2e.yaml
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egressnode/egressnode_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#302 pending e2e
  .github/workflows/call-e2e.yaml
Labels: release/none

#303 New design document. This document keeps the latest design later
  docs/develop/datapath/README.md
  docs/develop/datapath/README_zh-CN.md
  docs/develop/egress-cluster-status/README.md
  docs/develop/egress-cluster-status/README_zh-CN.md
  docs/develop/egress-endpoint-slice/README.md
  docs/develop/egress-endpoint-slice/README_zh-CN.md
  docs/develop/egress-gateway-policy-cluster/README.md
  docs/develop/egress-gateway-policy-cluster/README_zh-CN.md
  docs/develop/egress-gateway-policy/README.md
  docs/develop/egress-gateway-policy/README_zh-CN.md
  docs/develop/egress-gateway/README.md
  docs/develop/egress-gateway/README_zh-CN.md
  docs/develop/egress-node/README.md
  docs/develop/egress-node/README_zh-CN.md
Labels: documentation, release/none

#312 Pin trivy version to 0.36.0
  Makefile
Labels: release/none

#314 Remove unused files and optimize folder structure
  Makefile
  pkg/controller/allocator/allocator.go
  pkg/controller/allocator/interface.go
  pkg/controller/egress_node.go
  pkg/controller/node.go
  pkg/k8s/client/clientset/versioned/clientset.go
  pkg/k8s/client/clientset/versioned/doc.go
  pkg/k8s/client/clientset/versioned/fake/clientset_generated.go
  pkg/k8s/client/clientset/versioned/fake/doc.go
  pkg/k8s/client/clientset/versioned/fake/register.go
  pkg/k8s/client/clientset/versioned/scheme/doc.go
  pkg/k8s/client/clientset/versioned/scheme/register.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/doc.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/egressgateway.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/egressgateway.spidernet.io_client.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/egressgatewaypolicy.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/egressnode.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/fake/doc.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/fake/fake_egressgateway.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/fake/fake_egressgateway.spidernet.io_client.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/fake/fake_egressgatewaypolicy.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/fake/fake_egressnode.go
  pkg/k8s/client/clientset/versioned/typed/egressgateway.spidernet.io/v1/generated_expansion.go
  pkg/k8s/client/informers/externalversions/egressgateway.spidernet.io/interface.go
  pkg/k8s/client/informers/externalversions/egressgateway.spidernet.io/v1/egressgateway.go
  pkg/k8s/client/informers/externalversions/egressgateway.spidernet.io/v1/egressgatewaypolicy.go
  pkg/k8s/client/informers/externalversions/egressgateway.spidernet.io/v1/egressnode.go
  pkg/k8s/client/informers/externalversions/egressgateway.spidernet.io/v1/interface.go
  pkg/k8s/client/informers/externalversions/factory.go
  pkg/k8s/client/informers/externalversions/generic.go
  pkg/k8s/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/k8s/client/listers/egressgateway.spidernet.io/v1/egressgateway.go
  pkg/k8s/client/listers/egressgateway.spidernet.io/v1/egressgatewaypolicy.go
  pkg/k8s/client/listers/egressgateway.spidernet.io/v1/egressnode.go
  pkg/k8s/client/listers/egressgateway.spidernet.io/v1/expansion_generated.go
Labels: release/feature

#281 build image
  .github/workflows/build-image-base.yaml
  .github/workflows/call-release-image.yaml
Labels: release/none

#315 fix golangci-lint S1039 error
  pkg/controller/egress_cluster_info.go
  vendor/k8s.io/client-go/discovery/fake/discovery.go
  vendor/modules.txt
Labels: release/none

#318 Fix config.yaml line breaks in ConfigMap with tplvalues.render
  charts/README.md
  charts/templates/configmap.yaml
  charts/values.yaml
Labels: release/feature
