Repository spidernet-io/egressgateway, pull requests merged in 2023-11, with the labels that each got.

#912 Update chart-testing-action to v2.6.0
  .github/workflows/call-lint-chart.yaml
Labels: release/none

#910 Add Netlify
  .github/workflows/netlify.yml
Labels: release/none

#914 Optimize the code for checking whether Calico exists
  pkg/controller/egress_cluster_info/egress_cluster_info.go
  pkg/controller/egress_cluster_info/egress_cluster_info_internal_test.go
Labels: release/none

#908 Fix the spelling mistakes
  .github/ISSUE_TEMPLATE/bug.md
Labels: release/none

#921 Fix the policy's status check in the function in the e2e test
  test/e2e/common/egp.go
Labels: bug, release/none

#917 Fix the repetition of gateway name in e2e test
  test/e2e/common/beforeeach.go
  test/e2e/common/egp.go
  test/e2e/common/egw.go
  test/e2e/common/pod.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/none

#920 Fix the validation of the parameter in function GenIPPools
  test/e2e/common/pool.go
Labels: release/none

#922 Fix the issue of abnormal deletion of ipset
  pkg/agent/police.go
  pkg/controller/cluster_endpoint_slice.go
Labels: release/bug

#924 Update the webhook validation process for egressgateway
  pkg/egressgateway/egress_gateway_webhook.go
Labels: release/none

#905 Update egressgateway README
  README.md
  docs/README.en.md
  docs/README.zh.md
  docs/backends.md
  images/Egress-Gateway.png
  images/architecture01.png
Labels: release/none

#930 update en docs about about concepts and reference
  docs/concepts/Architecture.en.md
  docs/concepts/Architecture.zh.md
  docs/concepts/Datapath.en.md
  docs/concepts/Datapath.zh.md
  docs/reference/EgressClusterInfo.en.md
  docs/reference/EgressGateway.en.md
  docs/reference/EgressPolicy.en.md
  docs/reference/EgressPolicy.zh.md
  docs/reference/EgressTunnel.en.md
  docs/reference/EgressTunnel.zh.md
Labels: documentation, release/none

#925 fix: egw status update failed
  pkg/egressgateway/egress_gateway.go
Labels: bug, release/bug

#931 Update version to v0.3.0
  VERSION
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#932 Update docs style
  README.md
  docs/Egress-Gateway.png
  docs/README.en.md
  docs/README.zh.md
  docs/architecture.png
  docs/backends.md
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
Labels: release/none

#901 Add case P00021
  test/e2e/common/pod.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#940 Update release markdown
  docs/develop/release.md
Labels: release/none

#945 Update readme
  README.md
  docs/README.en.md
  docs/README.zh.md
  docs/architecture02.png
Labels: release/none

#944 Fix the validation of the policy's EIP format
  pkg/controller/webhook/validate.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: bug, release/none

#943 Update validation of egress gateway
  pkg/egressgateway/egress_gateway_webhook.go
Labels: release/none

#942 Fix the validation of the policy's PodSubnet and PodSelector
  pkg/controller/webhook/validate.go
  pkg/controller/webhook/validate_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: bug, release/none

#949 doc: fix format errors
  docs/concepts/Architecture.en.md
  docs/concepts/Architecture.zh.md
  docs/concepts/Datapath.zh.md
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
Labels: documentation, release/none

#954 Publish development documents through github actions.
  .github/workflows/call-release-pages.yaml
Labels: documentation, release/none

#955 fix install bug
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
Labels: release/none

#950 fix minor errors
  docs/reference/EgressPolicy.zh.md
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
Labels: release/none

#966 docs: format datapath.zh.md
  docs/concepts/Datapath.zh.md
Labels: documentation, release/none, kind/bug

#965 Fix the status of the egressgateway in the installation documents
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
Labels: documentation, release/none

#968 sync node status to egt
  charts/crds/egressgateway.spidernet.io_egresstunnels.yaml
  docs/reference/EgressTunnel.en.md
  docs/reference/EgressTunnel.zh.md
  pkg/agent/vxlan.go
  pkg/controller/egress_tunnel.go
  pkg/k8s/apis/v1beta1/egresstunnel_types.go
Labels: release/none

#969 fix: incorrect policy reassignment caused by egt
  pkg/egressgateway/egress_gateway.go
Labels: bug, release/bug

#970 Fix update egress gateway
  pkg/egressgateway/egress_gateway_webhook.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#972 Increase pod waiting time from 5 seconds to 10 seconds
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#974 Update pending test
  pkg/controller/webhook/validate.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#975 modify some documents
  docs/reference/EgressClusterPolicy.zh.md
  docs/reference/EgressGateway.zh.md
  docs/reference/EgressPolicy.zh.md
Labels: documentation, release/none

#988 Update controller-runtime to v0.16.3
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/controller/controller.go
  vendor/go.uber.org/multierr/CHANGELOG.md
  vendor/go.uber.org/multierr/error.go
  vendor/go.uber.org/multierr/error_post_go120.go
  vendor/go.uber.org/multierr/error_pre_go120.go
  vendor/golang.org/x/exp/maps/maps.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/VERSIONING.md
  vendor/sigs.k8s.io/controller-runtime/alias.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/delegating_by_gvk_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/transformers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/listener.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/server/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/server/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/decode.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: release/none

#986 Update the script for install-calico
  test/scripts/installCalico.sh
  test/yaml/calico.yaml
Labels: enhancement, release/none, kind/test

#989 Fix IP repetition when testing IPv6 allocation
  pkg/egressgateway/egress_gateway.go
Labels: bug, release/none

#981 open the test case R00008
  pkg/controller/webhook/validate.go
  pkg/egressgateway/egress_gateway.go
  test/e2e/reliability/reliability_ip_test.go
Labels: release/none, kind/test

#992 Reduce the data impact caused by EgressTunnel updates
  pkg/agent/vxlan.go
Labels: release/none

#1007 Update version to v0.4.0
  VERSION
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#1003 docs: replenishment datapath
  docs/concepts/Datapath.zh.md
Labels: documentation, release/none

#980 add: egw uses the EIP count function
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  pkg/egressgateway/egress_gateway.go
  pkg/k8s/apis/v1beta1/egressgateway_types.go
  pkg/k8s/apis/v1beta1/zz_generated.deepcopy.go
  pkg/utils/ip/ip.go
Labels: release/feature-new

#1008 Fix residual CR when uninstall egressgateway
  cmd/controller/cmd/clean.go
Labels: release/none

#1010 Add event for egress tunnel status changed
  pkg/controller/egress_tunnel.go
  pkg/k8s/apis/v1beta1/egresstunnel_types.go
Labels: release/feature-new

#1018 Update docs
  .github/codespell-ignorewords
  docs/mkdocs.yml
  docs/usage/EgressGatewayFailover.en.md
  docs/usage/EgressGatewayFailover.zh.md
  docs/usage/egress-check.svg
  docs/usage/primary-backup.svg
Labels: release/none

#1024 Update docs
  charts/README.md
  charts/values.yaml
  docs/Troubleshooting.en.md
  docs/Troubleshooting.zh.md
  docs/speed.svg
Labels: release/none
