Repository spidernet-io/egressgateway, pull requests merged in 2023-06, with the labels that each got.

#402 update crds: egressgateway.ranges -> egressgateway.ippools
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  docs/develop/egress-gateway/README_zh-CN.md
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressgateway_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/zz_generated.deepcopy.go
Labels: release/none

#411 added egressgateway support for defaultEIP
  charts/crds/egressgateway.spidernet.io_egressclusterpolicies.yaml
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  charts/crds/egressgateway.spidernet.io_egresspolicies.yaml
  charts/templates/tls.yaml
  pkg/controller/controller.go
  pkg/controller/webhook/validate.go
  pkg/egressgateway/egress_gateway.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressgateway_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egresspolicy_types.go
Labels: release/feature

#417 Update helm chart
  charts/README.md
  charts/templates/_helpers.tpl
  charts/templates/daemonset.yaml
  charts/templates/deployment.yaml
  charts/templates/grafanaDashboard.yaml
  charts/templates/pdb.yaml
  charts/templates/prometheusrule.yaml
  charts/templates/roleBinding.yaml
  charts/templates/service.yaml
  charts/templates/serviceaccount.yaml
  charts/templates/servicemonitor.yaml
  charts/templates/tls.yaml
  charts/values.yaml
Labels: release/none

#418 Bump dependencies
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/internal/suite.go
  vendor/github.com/onsi/ginkgo/v2/reporters/json_report.go
  vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  vendor/github.com/onsi/ginkgo/v2/reporters/teamcity_report.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/pelletier/go-toml/v2/README.md
  vendor/github.com/pelletier/go-toml/v2/ci.sh
  vendor/github.com/pelletier/go-toml/v2/marshaler.go
  vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
  vendor/github.com/pelletier/go-toml/v2/unstable/ast.go
  vendor/github.com/pelletier/go-toml/v2/unstable/parser.go
  vendor/github.com/pelletier/go-toml/v2/unstable/scanner.go
  vendor/github.com/pyroscope-io/client/pyroscope/api.go
  vendor/github.com/pyroscope-io/client/upstream/remote/remote.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/github.com/spf13/afero/afero.go
  vendor/github.com/spf13/afero/basepath.go
  vendor/github.com/spf13/afero/copyOnWriteFs.go
  vendor/github.com/spf13/afero/ioutil.go
  vendor/github.com/spf13/afero/mem/file.go
  vendor/github.com/spf13/afero/memmap.go
  vendor/github.com/spf13/afero/regexpfs.go
  vendor/github.com/spf13/afero/symlink.go
  vendor/github.com/spf13/afero/unionFile.go
  vendor/github.com/spf13/afero/util.go
  vendor/github.com/spf13/cast/README.md
  vendor/github.com/spf13/cast/caste.go
  vendor/github.com/spf13/viper/.golangci.yaml
  vendor/github.com/spf13/viper/Makefile
  vendor/github.com/spf13/viper/README.md
  vendor/github.com/spf13/viper/util.go
  vendor/github.com/spf13/viper/viper.go
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: release/none

#415 [doc-zh] update docs/develop/egress-cluster-info/README_zh-CN.md
  docs/develop/egress-cluster-info/README.md
  docs/develop/egress-cluster-info/README_zh-CN.md
  docs/develop/egress-cluster-status/README_zh-CN.md
Labels: release/none

#425 Fix webhook definition has no file delimiter symbol
  charts/templates/tls.yaml
Labels: release/none

#429 Bump ginkgo to v2.10.0
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generate_command.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generate_templates.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generators_common.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/event/tag/tag.go
  vendor/golang.org/x/tools/internal/gcimporter/bexport.go
  vendor/golang.org/x/tools/internal/gcimporter/bimport.go
  vendor/golang.org/x/tools/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/ureader_yes.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: release/none

#413 Update policy controller
  pkg/agent/agent.go
  pkg/agent/police.go
  pkg/agent/route/route.go
  pkg/agent/vxlan.go
  pkg/agent/vxlan/vxlan.go
  pkg/agent/vxlan_test.go
  pkg/markallocator/allocator.go
Labels: release/feature

#433 Remove unused param of helm values
  charts/README.md
  charts/values.yaml
  pkg/config/config.go
  test/e2e/common/egressconfigmap.go
Labels: release/none

#434 Update e2e workflow
  .github/workflows/call-e2e.yaml
  Makefile.defs
  test/Makefile
  tools/golang/codeCoverage.sh
Labels: release/none

#441 Update "golang auto upgrade" workflow
  .github/workflows/update-golang-version.yaml
  Makefile
  Makefile.defs
Labels: release/none

#443 Update dependabot config
  .github/dependabot.yml
Labels: release/none

#445 robot Update project owing to updated Golang Version
  .github/workflows/call-e2e.yaml
  .github/workflows/lint-golang.yaml
  images/agent-base/Dockerfile
  images/agent/Dockerfile
  images/controller-base/Dockerfile
  images/controller/Dockerfile
  images/nettools-base/Dockerfile
  images/nettools/Dockerfile
Labels: pr/robot_update

#446 Egressgateway Supports the EgressClusterPolicy
  pkg/egressgateway/egress_gateway.go
Labels: release/feature

#452 Fix data race check of vxlan
  pkg/agent/vxlan/vxlan.go
Labels: release/bug

#451 Add datapath logic for ignore internal CIDR
  pkg/agent/police.go
Labels: release/feature

#436 [e2e doc] about egressgateway and egresspolicy
  docs/develop/dev.md
  test/doc/egressgateway.md
  test/doc/egressgateway_zh.md
  test/doc/egresspolicy.md
  test/doc/egresspolicy_zh.md
  test/doc/reliability.md
  test/doc/reliability_zh.md
  test/doc/stress.md
Labels: release/none

#469 fill default
  charts/crds/egressgateway.spidernet.io_egressclusterpolicies.yaml
  charts/crds/egressgateway.spidernet.io_egresspolicies.yaml
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egresspolicy_types.go
Labels: release/none

#470 Update helm chart
  charts/README.md
  charts/values.yaml
  pkg/config/config.go
Labels: release/none

#472 add crd field
  charts/crds/egressgateway.spidernet.io_egressclusterpolicies.yaml
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  charts/crds/egressgateway.spidernet.io_egresspolicies.yaml
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressclusterpolicy_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressgateway_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egresspolicy_types.go
Labels: release/none

#478 docs: update egw readme
  docs/develop/egress-gateway/README_zh-CN.md
Labels: release/none

#477 ci: test namespace
  Makefile.defs
  test/Makefile
  test/scripts/debugCluster.sh
Labels: release/none

#473 Update crd
  charts/crds/egressgateway.spidernet.io_egressclusterpolicies.yaml
  charts/crds/egressgateway.spidernet.io_egresspolicies.yaml
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressclusterendpointslice_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressclusterpolicy_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egresspolicy_types.go
Labels: release/none

#481 Fix the wrong return not found error of get policy subnet func
  pkg/agent/eip.go
  pkg/agent/police.go
Labels: release/none

#480 Fix release image tag not update
  Makefile
Labels: release/none

#482 Fix return not found error
  pkg/agent/police.go
Labels: release/none

#487 Update docs website
  docs/mkdocs.yml
Labels: release/none

#484 Update rp_filter settting of vxlan
  pkg/agent/vxlan/vxlan.go
Labels: release/none

#489 Update website structure
  Makefile
  README.md
  docs/README.en.md
  docs/README.md
  docs/README.zh.md
  docs/Troubleshooting.en.md
  docs/Troubleshooting.zh.md
  docs/concepts/Architecture.en.md
  docs/concepts/Architecture.zh.md
  docs/concepts/Datapath.en.md
  docs/concepts/Datapath.zh.md
  docs/crds/EgressClusterEndpointSlice.en.md
  docs/crds/EgressClusterEndpointSlice.zh.md
  docs/crds/EgressClusterInfo.en.md
  docs/crds/EgressClusterInfo.zh.md
  docs/crds/EgressClusterPolicy.en.md
  docs/crds/EgressClusterPolicy.zh.md
  docs/crds/EgressEndpointSlice.en.md
  docs/crds/EgressEndpointSlice.zh.md
  docs/crds/EgressGateway.en.md
  docs/crds/EgressGateway.zh.md
  docs/crds/EgressNode.en.md
  docs/crds/EgressNode.zh.md
  docs/crds/EgressPolicy.en.md
  docs/crds/EgressPolicy.zh.md
  docs/develop/Contribute.en.md
  docs/develop/Dataflow.en.md
  docs/develop/Dataflow.zh.md
  docs/develop/Develop.en.md
  docs/develop/Release.en.md
  docs/develop/Roadmap.en.md
  docs/develop/dev.md
  docs/develop/egress-cluster-info/README.md
  docs/develop/egress-cluster-policy/README.md
  docs/develop/egress-endpoint-slice/README.md
  docs/develop/egress-gateway/README.md
  docs/develop/egress-node/README.md
  docs/develop/egress-policy/README.md
  docs/mkdocs.yml
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
  docs/usage/Uninstall.en.md
  docs/usage/Uninstall.zh.md
  docs/usage/Upgrade.en.md
  docs/usage/Upgrade.zh.md
Labels: release/none

#490 Update data flow png
  docs/proposal/03-egress-ip/arch.png
Labels: release/none

#491 Update installation docs
  docs/README.zh.md
  docs/mkdocs.yml
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
Labels: release/none

#493 chart: set tolerations
  charts/values.yaml
Labels: release/none

#488 fix e2e fialed get egressgateway configmap
  test/Makefile
  test/e2e/common/constant.go
  test/e2e/common/deployment.go
  test/e2e/common/egressconfigmap.go
Labels: release/none

#495 fix e2e cover
  tools/golang/e2ecover.sh
Labels: release/none

#500 fix e2e cover
  tools/golang/e2ecover.sh
Labels: release/none

#499 Update docs
  docs/README.zh.md
  docs/proposal/05-egress-gateway-policy-cluster/README_zh-CN.md
Labels: release/none

#502 feat/update version v0.2.0-rc1
  VERSION
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#507 robot update changelog with tag v0.2.0-rc1 to branch github_pages
  changelogs/changelog_from_v0.2.0-rc0_to_v0.2.0-rc1.md
Labels: pr/robot_update

#508 Update docs link
  docs/README.en.md
  docs/README.zh.md
Labels: release/none

#518 Fix log wrapper
  pkg/agent/eip.go
Labels: release/none

#517 Fix get egressgateway parameter
  pkg/agent/police.go
Labels: release/none

#516 Fix IPv6 does not support rp_filter
  pkg/agent/vxlan/vxlan.go
Labels: release/none

#519 Fix update endpoint slice
  pkg/agent/eip.go
  pkg/agent/police.go
  pkg/controller/endpoint_slice.go
Labels: release/none

#521 Fix rebuild cache
  pkg/controller/egress_node.go
Labels: release/none

#522 egw add additional Printer Columns
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressgateway_types.go
Labels: release/none

#524 Fix egressgateway webhook error when create (#449)
  pkg/egressgateway/egress_gateway_webhook.go
Labels: release/none

#523 Fix path join empty will not add ''/'
  pkg/agent/police.go
  pkg/utils/flat.go
Labels: release/none

#527 Fix ns join
  pkg/utils/flat.go
Labels: release/none

#528 Fix get started link
  README.md
Labels: release/none

#529 Update get started (en)
  docs/usage/Install.en.md
Labels: release/none

#530 Fix pod ip change not update EgressClusterEndpointSlice
  pkg/controller/cluster_endpoint_slice.go
  pkg/controller/endpoint_slice.go
Labels: release/none

#531 Fix auto cherry pick workflow
  .github/workflows/auto-cherrypick.yaml
Labels: release/none

#532 Update docs
  docs/crds/EgressClusterEndpointSlice.en.md
  docs/crds/EgressClusterEndpointSlice.zh.md
  docs/crds/EgressEndpointSlice.en.md
  docs/crds/EgressEndpointSlice.zh.md
  docs/develop/Release.en.md
Labels: release/none
