Repository spidernet-io/egressgateway, pull requests merged in 2023-08, with the labels that each got.

#668 Update calico ippool
  test/e2e/common/eip.go
  test/yaml/calico.yaml
Labels: release/none

#672 add retry when install kwok
  test/scripts/installKwok.sh
Labels: release/none

#651 Update egress unit test
  Makefile
  charts/crds/egressgateway.spidernet.io_egresstunnels.yaml
  pkg/agent/police.go
  pkg/agent/police_test.go
  pkg/agent/vxlan.go
  pkg/agent/vxlan/vxlan_test.go
  pkg/agent/vxlan_test.go
  pkg/config/config_test.go
  pkg/controller/cluster_endpoint_slice_test.go
  pkg/controller/egress_cluster_info.go
  pkg/controller/endpoint_slice_test.go
  pkg/controller/webhook/validate.go
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/k8s/apis/v1beta1/egressnode_types.go
  pkg/utils/ip/errors.go
  pkg/utils/ip/ip.go
  pkg/utils/ip/ip_test.go
  pkg/utils/ip_test.go
  pkg/utils/node.go
  pkg/utils/utils_suite_test.go
  test/e2e/common/calico.go
  test/e2e/common/clusterip.go
  test/e2e/common/ip.go
  test/e2e/common/node.go
Labels: release/none

#681 ci: check lock
  .github/workflows/lint-golang.yaml
  Makefile
  pkg/agent/vxlan/vxlan.go
  pkg/iptables/lock.go
Labels: release/none

#674 [e2e doc] update e2e testcase doc for egressClusterInfo
  test/doc/egressclusterinfo.md
  test/doc/egressclusterinfo_zh.md
Labels: release/none

#692 Add workflow for nettool image
  .github/workflows/build-image-base.yaml
  .github/workflows/call-release-image.yaml
  cmd/nettools/client/main.go
  cmd/nettools/server/main.go
Labels: release/feature

#686 the crd default value does not take effect
  charts/crds/egressgateway.spidernet.io_egressclusterpolicies.yaml
  charts/crds/egressgateway.spidernet.io_egresspolicies.yaml
  docs/usage/Install.zh.md
  pkg/controller/webhook/validate.go
  pkg/k8s/apis/v1beta1/egressclusterpolicy_types.go
  pkg/k8s/apis/v1beta1/egresspolicy_types.go
  test/doc/egresspolicy.md
  test/doc/egresspolicy_zh.md
  test/e2e/common/egresspolicy.go
  test/e2e/egresspolicy/egresspolicy_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/none

#683 Add default egw
  .github/codespell-ignorewords
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  charts/templates/tls.yaml
  docs/mkdocs.yml
  docs/usage/ClusterDefaultEgressGateway.en.md
  docs/usage/ClusterDefaultEgressGateway.zh.md
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
  docs/usage/NamespaceDefaultEgressGateway.en.md
  docs/usage/NamespaceDefaultEgressGateway.zh.md
  go.mod
  pkg/controller/controller.go
  pkg/controller/webhook/mutating.go
  pkg/controller/webhook/validate.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/k8s/apis/v1beta1/egressgateway_types.go
  pkg/k8s/apis/v1beta1/labels.go
  test/doc/egressgateway_zh.md
  test/e2e/egressgateway/default_egressgateway_test.go
Labels: release/feature, kind/feature

#684 [e2e doc] update e2e case doc R00007, restart all components in cluster
  test/doc/reliability.md
  test/doc/reliability_zh.md
Labels: release/none

#695 Update iptables comments
  pkg/agent/police.go
Labels: release/feature

#691 egw supports node status
  charts/crds/egressgateway.spidernet.io_egresstunnels.yaml
  docs/concepts/Architecture.zh.md
  docs/proposal/01-egress-gateway/EgressGateway.md
  docs/proposal/02-egress-node/EgressNode-zh_CN.md
  docs/proposal/03-egress-ip/README_zh-CN.md
  docs/reference/EgressGateway.zh.md
  docs/reference/EgressNode.en.md
  docs/reference/EgressNode.zh.md
  docs/usage/Install.zh.md
  pkg/agent/vxlan.go
  pkg/controller/egress_cluster_policy.go
  pkg/controller/egress_policy.go
  pkg/controller/egress_tunnel.go
  pkg/egressgateway/egress_gateway.go
  pkg/k8s/apis/v1beta1/egressnode_types.go
  test/doc/egressgateway_zh.md
  test/e2e/common/egressnode.go
Labels: release/none

#630 update egci crd
  .github/workflows/helm.yml
  charts/README.md
  charts/crds/egressgateway.spidernet.io_egressclusterinfos.yaml
  charts/templates/egressClusterInfo.yaml
  charts/values.yaml
  docs/proposal/04-auto-detect-egress-ignore-cidr/README_zh-CN.md
  docs/reference/EgressClusterInfo.en.md
  docs/reference/EgressClusterInfo.zh.md
  pkg/agent/police.go
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/controller/egress_cluster_info.go
  pkg/controller/egress_cluster_info/egress_cluster_info.go
  pkg/controller/egress_cluster_info/tools.go
  pkg/k8s/apis/v1beta1/egressclusterinfo_types.go
  pkg/k8s/apis/v1beta1/zz_generated.deepcopy.go
  pkg/lock/lock_debug.go
  pkg/utils/ip/ip.go
  pkg/utils/ip/ip_test.go
  test/e2e/common/constant.go
  test/e2e/common/egressclusterinfo.go
  test/e2e/common/egressconfigmap.go
  test/e2e/common/ip.go
  test/e2e/egressclusterinfo/egressclusterinfo_suite_test.go
  test/e2e/egressclusterinfo/egressclusterinfo_test.go
  test/e2e/err/err.go
Labels: release/none

#708 [e2e] fix install kwok
  Makefile.defs
  test/Makefile
  test/scripts/installKwok.sh
Labels: release/none

#703 Reduce unnecessary routes
  pkg/agent/route/route.go
  pkg/agent/vxlan.go
Labels: release/feature

#724 Update docs
  docs/mkdocs.yml
  docs/usage/ClusterDefaultEgressGateway.en.md
  docs/usage/Install.zh.md
  docs/usage/NamespaceDefaultEgressGateway.en.md
  docs/usage/Uninstall.en.md
  docs/usage/Uninstall.zh.md
Labels: release/none

#725 optimize log output
  pkg/agent/eip.go
  pkg/agent/police.go
  pkg/controller/cluster_endpoint_slice.go
  pkg/controller/egress_policy.go
  pkg/controller/egress_tunnel.go
  pkg/controller/endpoint_slice.go
  pkg/egressgateway/egress_gateway.go
Labels: release/feature

#726 Update version
  VERSION
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#723 egw supports empty ippool
  pkg/controller/webhook/validate.go
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway_webhook.go
  test/doc/egressgateway_zh.md
  test/doc/egresspolicy_zh.md
Labels: release/none

#730 change the EgressNode to EgressTunnel
  README.md
  charts/crds/egressgateway.spidernet.io_egressclusterpolicies.yaml
  docs/README.en.md
  docs/README.zh.md
  docs/concepts/Architecture.zh.md
  docs/mkdocs.yml
  docs/proposal/01-egress-gateway/EgressGateway.md
  docs/proposal/02-egress-node/EgressTunnel-zh_CN.md
  docs/proposal/03-egress-ip/README_zh-CN.md
  docs/reference/EgressTunnel.en.md
  docs/reference/EgressTunnel.zh.md
  docs/usage/Install.zh.md
  docs/usage/Uninstall.en.md
  docs/usage/Uninstall.zh.md
  pkg/agent/agent.go
  pkg/agent/police.go
  pkg/agent/vxlan.go
  pkg/controller/controller.go
  pkg/controller/egress_tunnel.go
  pkg/controller/egress_tunnel_test.go
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/k8s/apis/v1beta1/egressclusterpolicy_types.go
  pkg/k8s/apis/v1beta1/egresstunnel_types.go
  pkg/k8s/apis/v1beta1/zz_generated.deepcopy.go
  test/doc/reliability.md
  test/doc/reliability_zh.md
  test/e2e/common/egressnode.go
  test/e2e/common/egresstunnel.go
  test/e2e/common/ip.go
  test/e2e/egressgateway/default_egressgateway_test.go
  test/e2e/egresstunnel/egresstuneel_suite_test.go
  test/e2e/egresstunnel/egresstunnel_test.go
Labels: release/none

#734 Fix changelog
  tools/scripts/changelog.sh
Labels: release/none

#736 robot update changelog with tag v0.2.0 to branch github_pages
  changelogs/changelog_from_v0.1.0_to_v0.2.0.md
Labels: pr/robot_update

#728 add unitest
  pkg/controller/controller_test.go
  pkg/controller/webhook/mutating_test.go
  pkg/logger/logger_test.go
  pkg/markallocator/allocator_test.go
  pkg/utils/flat_test.go
  pkg/utils/map_test.go
  pkg/utils/node_test.go
Labels: release/none
