Repository spidernet-io/egressgateway, pull requests merged in 2023-12, with the labels that each got.

#1019 Add finalizer to egressgateway
  cmd/controller/cmd/clean.go
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
  pkg/controller/webhook/mutating.go
  pkg/egressgateway/egress_gateway.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/utils/slice/slice.go
  pkg/utils/slice/slice_test.go
  test/doc/egressgateway.md
  test/doc/egressgateway_zh.md
  test/e2e/egressgateway/egressgateway_test.go
Labels: release/feature-changed

#959 Verify that the EIP within the IP address ranges configured in the ippools of the egressgateway
  pkg/controller/webhook/validate.go
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/utils/ip/ip.go
  pkg/utils/ip/ip_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#1035 Supports publishing rc versions of docs to dev
  .github/workflows/call-release-pages.yaml
Labels: documentation, release/none

#1037 Fix check eip in dual stack
  pkg/controller/webhook/validate.go
Labels: release/bug

#982 Add e2e case S00001
  test/doc/egressendpointslice.md
  test/doc/egressendpointslice_zh.md
  test/e2e/common/check_eip.go
  test/e2e/common/deploy.go
  test/e2e/common/egep.go
  test/e2e/common/egp.go
  test/e2e/common/pod.go
  test/e2e/egressendpointslice/egressendpointslice_suite_test.go
  test/e2e/egressendpointslice/egressendpointslice_test.go
  test/e2e/tools/tools.go
Labels: release/none, kind/e2e

#1040 Fix check for duplicate EgressGateway
  pkg/egressgateway/egress_gateway_webhook.go
Labels: release/bug

#1033 Add the test case P00002 about default gateway
  test/e2e/common/egp.go
  test/e2e/egressendpointslice/egressendpointslice_test.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/none, kind/e2e

#1041 Add test case P00012
  test/doc/egressclusterinfo.md
  test/doc/egressclusterinfo_zh.md
  test/doc/egressendpointslice.md
  test/doc/egressendpointslice_zh.md
  test/doc/egressgateway.md
  test/doc/egressgateway_zh.md
  test/doc/egresspolicy.md
  test/doc/egresspolicy_zh.md
  test/e2e/common/ds.go
  test/e2e/common/eci.go
  test/e2e/common/pod.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none, kind/e2e

#1057 update test case R00005
  Makefile.defs
  test/Makefile
  test/e2e/common/check_eip.go
  test/e2e/common/egw.go
  test/e2e/common/node.go
  test/e2e/common/pod.go
  test/e2e/reliability/reliability_suite_test.go
  test/e2e/reliability/reliability_test.go
  test/e2e/tools/tools.go
Labels: release/none, kind/e2e

#1083 Update image
  docs/architecture02.png
Labels: documentation, release/none

#1084 Change upload-artifact from v4.0.0 to v3.1.3
  .github/workflows/auto-release.yaml
  .github/workflows/build-image-base.yaml
  .github/workflows/call-e2e.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/call-release-pages.yaml
  .github/workflows/call-trivy.yaml
  .github/workflows/helm.yml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-yaml.yaml
Labels: release/none, kind/ci-bug

#1089 Update unit test
  codecov.yml
  pkg/lock/lock_debug_test.go
  pkg/utils/ip/ip.go
  pkg/utils/ip/ip_test.go
Labels: release/none

#1092 Add unit test
  codecov.yml
  pkg/controller/cluster_endpoint_slice_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/egress_cluster_info/egress_cluster_info_internal_test.go
  pkg/controller/endpoint/cluster_endpoint_slice.go
  pkg/controller/endpoint/cluster_endpoint_slice_test.go
  pkg/controller/endpoint/endpoint_slice.go
  pkg/controller/endpoint/endpoint_slice_test.go
  pkg/controller/metrics/metrics.go
  pkg/controller/policy/egress_cluster_policy.go
  pkg/controller/policy/egress_policy.go
  pkg/controller/tunnel/egress_tunnel.go
  pkg/controller/tunnel/egress_tunnel_test.go
  pkg/lock/lock_debug_test.go
  pkg/lock/lock_fast_test.go
  pkg/lock/lock_suite_test.go
  pkg/logger/logger_test.go
  pkg/utils/flat_test.go
Labels: release/none

#1094 supplement config unit test
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  vendor/github.com/agiledragon/gomonkey/v2/LICENSE
  vendor/github.com/agiledragon/gomonkey/v2/README.md
  vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
  vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_amd64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_arm64.go
  vendor/github.com/agiledragon/gomonkey/v2/jmp_loong64.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
  vendor/github.com/agiledragon/gomonkey/v2/modify_binary_windows.go
  vendor/github.com/agiledragon/gomonkey/v2/patch.go
  vendor/github.com/agiledragon/gomonkey/v2/write_darwin_amd64.s
  vendor/github.com/agiledragon/gomonkey/v2/write_darwin_arm64.s
  vendor/modules.txt
Labels: release/none

#1095 add ut
  pkg/utils/ip/ip_test.go
Labels: release/none
