Repository spidernet-io/egressgateway, pull requests merged in 2023-03, with the labels that each got.

#184 Fix pages style
  docs/develop/dev.md
  docs/mkdocs.yml
  docs/proposal/02-egress-node/EgressNode-zh_CN.md
  docs/usage/install.md
  docs/usage/usage.md
Labels: release/none

#196 Update helm chart
  .github/workflows/update-chart-readme.yml
  charts/README.md
  charts/templates/configmap.yaml
  charts/templates/daemonset.yaml
  charts/templates/deployment.yaml
  charts/values.yaml
Labels: release/none

#206 nettools for testing
  Makefile
  cmd/nettools/client/main.go
  cmd/nettools/server/main.go
  go.mod
  go.sum
  images/nettools-base/Dockerfile
  images/nettools-base/build-gops.sh
  images/nettools-base/configure-iptables-wrapper.sh
  images/nettools-base/install-others.sh
  images/nettools-base/iptables-wrapper
  images/nettools-base/sources.list
  images/nettools/Dockerfile
  test/yaml/testclient.yaml
  test/yaml/testserver.yaml
  vendor/github.com/gorilla/websocket/.gitignore
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/client_clone.go
  vendor/github.com/gorilla/websocket/client_clone_legacy.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_write.go
  vendor/github.com/gorilla/websocket/conn_write_legacy.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/join.go
  vendor/github.com/gorilla/websocket/json.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/mask_safe.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/trace.go
  vendor/github.com/gorilla/websocket/trace_17.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/modules.txt
Labels: release/feature

#210 Fixed the issue where EgressGateway creation preceded node labeling.
  pkg/controller/egress_gateway.go
Labels: release/bug

#220 Avoid null value when serializing operations
  pkg/k8s/apis/egressgateway.spidernet.io/v1/egressgatewaynode_types.go
Labels: release/bug

#223 Update resource limit
  charts/values.yaml
Labels: release/none

#227 Fix CI of helm
  .github/workflows/helm.yml
  .github/workflows/update-chart-readme.yml
Labels: release/none

#228 Update helm values.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#231 bump actions/setup-go from 3 to 4
  .github/workflows/call-e2e.yaml
  .github/workflows/lint-golang.yaml
  go.mod
Labels: release/none

#233 Update release version
  VERSION
  charts/Chart.yaml
Labels: release/none

#235 Update docker login action
  .github/workflows/build-image-base.yaml
  .github/workflows/call-release-image.yaml
Labels: release/none

#236 Fix release CI
  .github/workflows/auto-release.yaml
  .github/workflows/call-release-pages.yaml
  tools/scripts/changelog.sh
Labels: release/none

#237 robot Update doc from to branch github_pages
  docs/404.html
  docs/assets/javascripts/bundle.19047be9.min.js
  docs/assets/javascripts/bundle.19047be9.min.js.map
  docs/assets/javascripts/bundle.2a6f1dda.min.js
  docs/assets/javascripts/bundle.2a6f1dda.min.js.map
  docs/assets/stylesheets/main.113286f1.min.css
  docs/assets/stylesheets/main.113286f1.min.css.map
  docs/assets/stylesheets/main.240905d7.min.css
  docs/assets/stylesheets/main.240905d7.min.css.map
  docs/charts/egressgateway-0.1.0.tgz
  docs/develop/dev/index.html
  docs/index.yaml
  docs/mkdocs.yml
  docs/proposal/01-egress-gateway/Egress Gateway.png
  docs/proposal/02-egress-node/EgressNode-zh_CN/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  docs/usage/install/index.html
Labels: pr/robot_update

#238 robot update changelog with tag v0.1.0 to branch github_pages
  changelogs/changelog_from__to_v0.1.0.md
Labels: pr/robot_update

#239 Fix helm package
  .github/workflows/call-lint-chart.yaml
  .github/workflows/call-release-pages.yaml
  Makefile
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#241 robot update changelog with tag v0.1.0 to branch github_pages
  changelogs/changelog_from__to_v0.1.0.md
Labels: pr/robot_update

#240 robot Update doc from to branch github_pages
  docs/charts/egressgateway-0.1.0.tgz
  docs/index.yaml
  docs/sitemap.xml.gz
Labels: pr/robot_update

#247 Update homepage and install docs
  docs/README.md
  docs/mkdocs.yml
  docs/usage/Install.md
  docs/usage/install.md
Labels: release/feature

#249 Support running e2e on different os to test the iptables legacy mode
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-e2e.yaml
Labels: release/feature

#248 add e2e doc and badge
  .github/workflows/badge.yaml
  README.md
  test/doc/egressgateway.md
  test/doc/egressnode.md
  test/doc/egresspolicy.md
  test/doc/stress.md
  tools/golang/e2ecover.sh
Labels: release/none

#251 Fix e2ecover.sh permission denied
  tools/golang/e2ecover.sh
Labels: release/none

#253 install calico after created kind cluster
  Makefile.defs
  test/Makefile
  test/scripts/installCalico.sh
  test/yaml/calico.yaml
Labels: release/none

#252 Fix the spacing issue in gitHub actions config
  .github/workflows/call-e2e.yaml
Labels: release/none

#255 Update the required property of the “os” field in e2e CI
  .github/workflows/call-e2e.yaml
Labels: release/none

#256 Fix e2e render variables
  .github/workflows/call-e2e.yaml
Labels: release/none

#250 Update iptables rule match criteria
  pkg/agent/police.go
  pkg/agent/police_test.go
Labels: release/feature

#258 run nettools server and run e2e
  Makefile.defs
  test/Makefile
  test/e2e/common/constant.go
  test/e2e/common/deployment.go
  test/e2e/common/egressconfigmap.go
  test/e2e/common/egressgateway.go
  test/e2e/common/egressnode.go
  test/e2e/common/egresspolicy.go
  test/e2e/common/err.go
  test/e2e/common/ip.go
  test/e2e/common/iptables.go
  test/e2e/common/node.go
  test/e2e/egressgateway/egressgateway_suite_test.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egressnode/egressnode_suite_test.go
  test/e2e/egressnode/egressnode_test.go
  test/e2e/egresspolicy/egresspolicy_suite_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
  test/e2e/err/err.go
  test/e2e/tools/tools.go
  test/kindconfig/global-kind.yaml
  test/scripts/check-nettools-server.sh
Labels: release/none

#263 update readme
  README.md
Labels: release/none
