Repository spidernet-io/egressgateway, pull requests merged in 2023-05, with the labels that each got.

#331 add webhook about delete egressClusterInfo
  charts/templates/tls.yaml
  charts/values.yaml
  pkg/controller/egress_cluster_info.go
  pkg/controller/webhook/validate.go
Labels: release/none

#334 open the call-e2e ci yaml
  .github/workflows/call-e2e.yaml
Labels: release/none

#343 Fix authorization error watching
  charts/templates/role.yaml
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/rbac.go
Labels: release/none

#341 Modify the label used for CI failures
  .github/workflows/auto-nightly-ci.yaml
Labels: release/none

#357 [fix] change from obtaining k8s cidr from api-server to obtaining it from c…
  pkg/controller/egress_cluster_info.go
Labels: release/none

#354 implement the new EgressGateway controller and webhook
  charts/crds/egressgateway.spidernet.io_egressgateways.yaml
  go.mod
  pkg/constant/constant.go
  pkg/controller/controller.go
  pkg/controller/egress_gateway.go
  pkg/controller/webhook/validate.go
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressgateway_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/zz_generated.deepcopy.go
  pkg/utils/errors.go
  pkg/utils/ip.go
Labels: release/feature, kind/feature

#358 Update crds
  charts/crds/egressgateway.spidernet.io_egressclusterendpointslices.yaml
  charts/crds/egressgateway.spidernet.io_egressclusterpolicies.yaml
  charts/crds/egressgateway.spidernet.io_egressendpointslices.yaml
  charts/crds/egressgateway.spidernet.io_egresspolicies.yaml
  charts/templates/role.yaml
  pkg/agent/eip.go
  pkg/controller/cluster_endpoint_slice.go
  pkg/controller/endpoint_slice.go
  pkg/controller/endpoint_slice_test.go
  pkg/controller/webhook/validate.go
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressclusterpolicy_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressendpointslice_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egresspolicy_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/rbac.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/zz_generated.deepcopy.go
Labels: release/none

#361 ci: multiple k8s version
  .github/workflows/auto-nightly-ci.yaml
  .github/workflows/auto-pr-ci.yaml
  .github/workflows/call-e2e.yaml
  Makefile.defs
  test/Makefile
Labels: release/none

#375 Update docs
  docs/develop/contribute.md
  docs/develop/release.md
Labels: release/none

#310 Update egress node controller
  charts/crds/egressgateway.spidernet.io_egressnodes.yaml
  pkg/config/config.go
  pkg/controller/controller.go
  pkg/controller/egress_node.go
  pkg/controller/egress_node_test.go
  pkg/ipam/ipam.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressclusterinfo_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressendpointslice_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressgateway_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressnode_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egresspolicy_types.go
  pkg/markallocator/allocator.go
  pkg/schema/schema.go
  tools/golang/crdSdkGen.sh
Labels: release/none

#374 fix: egressgateway->delete、egresspolicy->delete webhook failed
  charts/templates/tls.yaml
  pkg/controller/webhook/validate.go
  pkg/egressgateway/egress_gateway_webhook.go
Labels: release/none

#376 Fix egress policy version of validate
  pkg/controller/webhook/validate.go
Labels: release/none

#377 Fix vxlan controller
  pkg/agent/vxlan.go
Labels: release/none

#383 Fix github action
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-pages.yaml
Labels: release/none

#386 robot update changelog with tag v0.2.0-rc0 to branch github_pages
  changelogs/changelog_from_v0.1.0_to_v0.2.0-rc0.md
Labels: pr/robot_update

#389 Remove deprecated code
  pkg/agent/police.go
  pkg/agent/police_test.go
  pkg/agent/vxlan.go
  pkg/agent/vxlan_test.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1/doc.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1/egressgatewaynode_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1/egressgatewaypolicy_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1/egressnode_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1/groupversion_info.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1/rbac.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1/register.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1/zz_generated.deepcopy.go
  pkg/utils/node.go
  test/e2e/common/egressgateway.go
  test/e2e/common/egressnode.go
  test/e2e/common/egresspolicy.go
Labels: release/none

#390 add egresspolicy webhook
  pkg/controller/webhook/validate.go
  pkg/controller/webhook/validate_test.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egresspolicy_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/zz_generated.deepcopy.go
Labels: release/none

#392 update egresspolicy crd
  pkg/controller/endpoint_slice_test.go
  pkg/controller/webhook/validate_test.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egresspolicy_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/zz_generated.deepcopy.go
  test/e2e/common/egresspolicy.go
Labels: release/none

#394 Fix changelog script
  tools/scripts/changelog.sh
Labels: release/none

#395 robot Update doc from to branch github_pages
  docs/404.html
  docs/assets/stylesheets/main.26e3688c.min.css
  docs/assets/stylesheets/main.26e3688c.min.css.map
  docs/assets/stylesheets/main.85bb2934.min.css
  docs/assets/stylesheets/main.85bb2934.min.css.map
  docs/assets/stylesheets/palette.a6bdf11c.min.css
  docs/assets/stylesheets/palette.a6bdf11c.min.css.map
  docs/assets/stylesheets/palette.ecc896b0.min.css
  docs/assets/stylesheets/palette.ecc896b0.min.css.map
  docs/charts/egressgateway-0.2.0-rc0.tgz
  docs/develop/contribute/index.html
  docs/develop/datapath/README_zh-CN/index.html
  docs/develop/datapath/index.html
  docs/develop/dev/index.html
  docs/develop/egress-cluster-gateway-policy/README_zh-CN/index.html
  docs/develop/egress-cluster-gateway-policy/index.html
  docs/develop/egress-cluster-status/README_zh-CN/index.html
  docs/develop/egress-cluster-status/index.html
  docs/develop/egress-endpoint-slice/README_zh-CN/index.html
  docs/develop/egress-endpoint-slice/index.html
  docs/develop/egress-gateway-policy/README_zh-CN/index.html
  docs/develop/egress-gateway-policy/index.html
  docs/develop/egress-gateway/README_zh-CN/index.html
  docs/develop/egress-gateway/index.html
  docs/develop/egress-node/README_zh-CN/index.html
  docs/develop/egress-node/index.html
  docs/develop/release/index.html
  docs/develop/roadmap/index.html
  docs/index.html
  docs/index.yaml
  docs/proposal/01-egress-gateway/EgressGateway/index.html
  docs/proposal/02-egress-node/EgressNode-zh_CN/index.html
  docs/proposal/03-egress-ip/README_zh-CN/index.html
  docs/proposal/04-auto-detect-egress-ignore-cidr/README_zh-CN/index.html
  docs/proposal/05-egress-gateway-policy-cluster/README_zh-CN/index.html
  docs/sitemap.xml.gz
  docs/usage/Install/index.html
Labels: pr/robot_update

#396 robot update changelog with tag v0.2.0-rc0 to branch github_pages
  changelogs/changelog_from_v0.1.0_to_v0.2.0-rc0.md
Labels: pr/robot_update

#399 Delete invalid use cases
  test/doc/egressgateway.md
  test/doc/egressnode.md
  test/doc/egresspolicy.md
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egressnode/egressnode_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none
