Repository spidernet-io/egressgateway, pull requests merged in 2023-07, with the labels that each got.

#533 fix: ippools is successfully created for empty
  pkg/egressgateway/egress_gateway_webhook.go
Labels: release/none

#536 Add uninstall docs
  docs/usage/Uninstall.en.md
  docs/usage/Uninstall.zh.md
Labels: release/none

#537 Update log structure
  charts/README.md
  charts/templates/daemonset.yaml
  charts/templates/deployment.yaml
  charts/values.yaml
  cmd/agent/cmd/root.go
  cmd/controller/cmd/root.go
  go.mod
  go.sum
  pkg/agent/agent.go
  pkg/agent/eip.go
  pkg/agent/police.go
  pkg/agent/route/route.go
  pkg/agent/vxlan.go
  pkg/agent/vxlan_test.go
  pkg/coalescing/coalescing.go
  pkg/config/config.go
  pkg/controller/cluster_endpoint_slice.go
  pkg/controller/controller.go
  pkg/controller/egress_cluster_info.go
  pkg/controller/egress_cluster_policy.go
  pkg/controller/egress_node.go
  pkg/controller/egress_node_test.go
  pkg/controller/egress_policy.go
  pkg/controller/endpoint_slice.go
  pkg/controller/endpoint_slice_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/iptables/table.go
  pkg/logger/logger.go
  pkg/logger/logsink.go
  pkg/profiling/manager.go
  vendor/github.com/go-logr/zapr/.gitignore
  vendor/github.com/go-logr/zapr/LICENSE
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/kube_helpers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
Labels: release/none

#544 Fix CRD name of docs
  docs/usage/Install.en.md
  docs/usage/Install.zh.md
Labels: release/none

#540 Remove id field in setup go steps
  .github/workflows/call-e2e.yaml
Labels: release/none

#539 Fix delete policy not update gateway status
  pkg/egressgateway/egress_gateway.go
Labels: release/bug

#543 Update title word capitalization
  docs/develop/Contribute.en.md
Labels: release/none

#542 Update egress policy docs
  docs/crds/EgressPolicy.en.md
  docs/crds/EgressPolicy.zh.md
Labels: release/none

#548 Add upgrade docs
  docs/usage/Upgrade.en.md
  docs/usage/Upgrade.zh.md
Labels: release/none

#547 Remove swagger SDK check of workflow
  .github/workflows/lint-golang.yaml
Labels: release/none

#550 Add support for 'squash and merge'
  .github/workflows/auto-cherrypick.yaml
Labels: release/none

#554 Add clean ipset function
  pkg/agent/police.go
Labels: release/none

#552 Update pyroscope settings
  charts/README.md
  charts/templates/daemonset.yaml
  charts/templates/deployment.yaml
  charts/values.yaml
  pkg/agent/agent.go
  pkg/controller/controller.go
  pkg/profiling/manager.go
  test/Makefile
Labels: release/none

#558 Update owners file
  CODEOWNERS
Labels: release/none

#549 Update egress cluster policy docs
  docs/crds/EgressClusterPolicy.en.md
  docs/crds/EgressClusterPolicy.zh.md
Labels: release/none

#559 update tls for egressclusterinfos
  charts/templates/tls.yaml
Labels: release/none

#560 Fix egress ip not work for ipv6
  charts/templates/deployment.yaml
  pkg/agent/eip.go
  pkg/config/config.go
  pkg/logger/logger.go
Labels: release/none

#561 Add ipset output logging
  pkg/ipset/ipset.go
Labels: release/none

#428 [e2e] create egressgateway
  go.mod
  test/e2e/common/calico.go
  test/e2e/common/constant.go
  test/e2e/common/deployment.go
  test/e2e/common/egressgateway.go
  test/e2e/common/egresspolicy.go
  test/e2e/common/eip.go
  test/e2e/common/err.go
  test/e2e/common/ip.go
  test/e2e/common/pod.go
  test/e2e/egressclusterinfo/egressclusterinfo_test.go
  test/e2e/egressgateway/egressgateway_suite_test.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egresspolicy/egresspolicy_suite_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
  test/e2e/tools/tools.go
Labels: release/none

#562 Fix load nettools image
  test/Makefile
Labels: release/none

#564 Update crd docs
  docs/concepts/Architecture.en.md
  docs/concepts/Architecture.zh.md
  docs/crds/EgressClusterInfo.en.md
  docs/crds/EgressClusterInfo.zh.md
  docs/crds/EgressGateway.zh.md
  docs/crds/EgressNode.en.md
  docs/crds/EgressNode.zh.md
Labels: release/none

#568 Rename EgressNode to EgressTunnel
  charts/crds/egressgateway.spidernet.io_egresstunnels.yaml
  charts/templates/role.yaml
  pkg/agent/police.go
  pkg/agent/vxlan.go
  pkg/agent/vxlan_test.go
  pkg/controller/egress_node.go
  pkg/controller/egress_node_test.go
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/egressnode_types.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/rbac.go
  pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/zz_generated.deepcopy.go
  test/e2e/common/egressnode.go
Labels: release/none

#572 fix tcp reset by peer
  test/e2e/common/constant.go
  test/e2e/common/eip.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#574 add kill exec process
  test/e2e/common/eip.go
Labels: release/none

#576 Update log instance with additional key/value pairs
  pkg/agent/eip.go
  pkg/agent/police.go
  pkg/controller/cluster_endpoint_slice.go
  pkg/controller/egress_cluster_info.go
  pkg/controller/endpoint_slice.go
  pkg/egressgateway/egress_gateway.go
Labels: release/none

#579 Update affinity nindent
  charts/templates/daemonset.yaml
  charts/templates/deployment.yaml
Labels: release/none

#582 Update log output
  pkg/egressgateway/egress_gateway.go
Labels: release/none

#588 Add ouput log for test
  test/Makefile
Labels: release/none

#587 Update check eip
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#586 add Webhooks for egpName and EIP
  pkg/controller/webhook/validate.go
Labels: release/none

#585 Update values
  charts/README.md
  charts/values.yaml
Labels: release/none

#590 Add origin link and changes of vendor code
  pkg/coalescing/coalescing.go
  pkg/iptables/interface.go
  pkg/lock/lock.go
  pkg/utils/set/set.go
Labels: release/none

#595 fix egressClusterInfo update with latest resourceVersion
  pkg/controller/egress_cluster_info.go
Labels: release/none

#604 fix egci nodeip repet
  pkg/controller/egress_cluster_info.go
Labels: release/none

#591 add: eip check in dual mode
  pkg/controller/webhook/validate.go
  pkg/egressgateway/egress_gateway.go
Labels: release/none

#589 add eip retry func
  cmd/nettools/client/main.go
  cmd/nettools/client/usage.md
  cmd/nettools/initFlag.go
  test/e2e/common/eip.go
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#606 fix e2e func GetAllNodesIP
  test/e2e/common/egressclusterinfo.go
  test/e2e/common/node.go
Labels: release/none

#609 optimise check egci fields
  test/e2e/common/egressclusterinfo.go
  test/e2e/egressclusterinfo/egressclusterinfo_test.go
Labels: release/none

#601 Add `announcedInterfacesToExclude` configurations
  charts/README.md
  charts/values.yaml
  pkg/agent/eip.go
  pkg/agent/police.go
  pkg/config/config.go
Labels: release/none

#611 Remove the usage output when running nettools
  cmd/nettools/initFlag.go
Labels: release/none

#610 Update iptables logs
  pkg/iptables/table.go
Labels: release/none

#603 e2e test install kwok
  test/Makefile
  test/e2e/common/constant.go
  test/e2e/common/kwok.go
  test/scripts/installKwok.sh
Labels: release/none

#577 Update import path
  pkg/agent/eip.go
  pkg/agent/police.go
  pkg/agent/vxlan.go
  pkg/agent/vxlan_test.go
  pkg/controller/cluster_endpoint_slice.go
  pkg/controller/egress_cluster_info.go
  pkg/controller/egress_cluster_policy.go
  pkg/controller/egress_node.go
  pkg/controller/egress_node_test.go
  pkg/controller/egress_policy.go
  pkg/controller/endpoint_slice.go
  pkg/controller/endpoint_slice_test.go
  pkg/controller/webhook/validate.go
  pkg/controller/webhook/validate_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/egressgateway/egress_gateway_webhook.go
  pkg/k8s/apis/v1beta1/egressclusterendpointslice_types.go
  pkg/k8s/apis/v1beta1/egressclusterinfo_types.go
  pkg/k8s/apis/v1beta1/egressclusterpolicy_types.go
  pkg/k8s/apis/v1beta1/egressendpointslice_types.go
  pkg/k8s/apis/v1beta1/egressgateway_types.go
  pkg/k8s/apis/v1beta1/egressnode_types.go
  pkg/k8s/apis/v1beta1/egresspolicy_types.go
  pkg/k8s/apis/v1beta1/groupversion_info.go
  pkg/k8s/apis/v1beta1/labels.go
  pkg/k8s/apis/v1beta1/rbac.go
  pkg/k8s/apis/v1beta1/register.go
  pkg/k8s/apis/v1beta1/zz_generated.deepcopy.go
  pkg/schema/schema.go
  test/e2e/common/egressclusterinfo.go
  test/e2e/common/egressgateway.go
  test/e2e/common/egressnode.go
  test/e2e/common/egresspolicy.go
  test/e2e/egressclusterinfo/egressclusterinfo_suite_test.go
  test/e2e/egressclusterinfo/egressclusterinfo_test.go
  test/e2e/egressgateway/egressgateway_suite_test.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egresspolicy/egresspolicy_suite_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
  tools/golang/crdControllerGen.sh
Labels: release/none

#566 e2e R00005: test eip drift after node shut down
  go.mod
  test/Makefile
  test/e2e/common/constant.go
  test/e2e/common/egressgateway.go
  test/e2e/common/eip.go
  test/e2e/common/marshal.go
  test/e2e/common/node.go
  test/e2e/common/pod.go
  test/e2e/reliability/reliability_suite_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/none

#618 add a new nettools server,use as a blacklist test
  Makefile.defs
  test/Makefile
  test/e2e/common/constant.go
  test/e2e/egresspolicy/egresspolicy_suite_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
  test/scripts/check-nettools-server.sh
Labels: release/none

#635 e2e P00011: access egci external traffic
  test/e2e/egresspolicy/egresspolicy_suite_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
  test/e2e/reliability/reliability_suite_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/none

#639 update e2e case doc
  test/doc/egressclusterinfo.md
  test/doc/egressgateway.md
  test/doc/egressgateway_zh.md
  test/doc/egresspolicy.md
  test/doc/egresspolicy_zh.md
  test/doc/reliability.md
  test/doc/reliability_zh.md
  test/e2e/egresspolicy/egresspolicy_test.go
Labels: release/none

#640 Update version to v0.2.0-rc2
  VERSION
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#632 Fix nightly ci
  .github/workflows/auto-pr-ci.yaml
Labels: release/none

#637 cancel egci test case
  test/e2e/common/egressclusterinfo.go
  test/e2e/egressclusterinfo/egressclusterinfo_suite_test.go
  test/e2e/egressclusterinfo/egressclusterinfo_test.go
Labels: release/none

#617 [E2E] G00005, create `egressgateway` using empty `DefaultEIP`
  test/e2e/common/egressgateway.go
  test/e2e/egressgateway/egressgateway_suite_test.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/tools/tools.go
Labels: release/none

#643 robot update changelog with tag v0.2.0-rc2 to branch github_pages
  changelogs/changelog_from_v0.2.0-rc1_to_v0.2.0-rc2.md
Labels: pr/robot_update

#650 fix bug and optimize for doc and E2E
  .github/workflows/helm.yml
  Makefile
  Makefile.defs
  charts/README.md
  charts/values.yaml
  docs/develop/Develop.en.md
  docs/usage/Install.zh.md
  test/Makefile
  test/kindconfig/global-kind.yaml
  test/scripts/installCalico.sh
  test/scripts/installKwok.sh
Labels: release/none
