Repository spidernet-io/egressgateway, pull requests merged in 2024-02, with the labels that each got.

#1190 Fix helm render values of agent pyroscope server addr
  charts/templates/daemonset.yaml
Labels: release/bug

#1192 add signoff for cherry-pick robot
  .github/workflows/auto-cherrypick.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-pages.yaml
Labels: release/none

#1195 fix 'Failed to combine cover profiles'
  pkg/agent/route/route_test.go
  pkg/agent/vxlan/vxlan_test.go
  pkg/config/config_test.go
  pkg/controller/egress_cluster_info/egress_cluster_info_test.go
  pkg/controller/endpoint/cluster_endpoint_slice_test.go
  pkg/controller/endpoint/endpoint_slice_test.go
  pkg/markallocator/allocator_test.go
Labels: release/none, kind/test

#1197 fix time out to wait egressgateway status to be empty after delete the polices
  test/e2e/reliability/reliability_ip_test.go
Labels: release/none

#1232 automatically port the label from the initial cherry-picked PR
  .github/workflows/auto-cherrypick.yaml
Labels: release/none
