Repository spidernet-io/egressgateway, pull requests merged in 2024-03, with the labels that each got.

#1244 Update roadmap
  docs/develop/Roadmap.en.md
Labels: release/none, release/docs

#1178 Add clean egress
  .github/workflows/call-e2e.yaml
  Makefile
  test/Makefile
Labels: release/none

#1249 Fix create egress gateway when allocate policy empty
  pkg/egressgateway/egress_gateway.go
Labels: release/bug

#1247 Fix make clean effort for e2e_init
  test/Makefile
Labels: release/bug

#1248 Fix RemoveFinalizers to improve code reusability
  pkg/controller/tunnel/egress_tunnel.go
  pkg/controller/tunnel/egress_tunnel_test.go
  pkg/egressgateway/egress_gateway.go
  pkg/utils/finalizers.go
  pkg/utils/finalizers_test.go
Labels: release/bug

#1253 Add move(migrate) egress IP cmd
  Makefile
  cmd/egctl/cmd/root.go
  cmd/egctl/cmd/vip.go
  cmd/egctl/main.go
  docs/mkdocs.yml
  docs/reference/egctl.en.md
  docs/reference/egctl.zh.md
  docs/usage/MoveIP.en.md
  docs/usage/MoveIP.zh.md
  images/controller/Dockerfile
  pkg/agent/eip.go
  pkg/agent/police.go
  pkg/egressgateway/egress_gateway.go
  test/e2e/egctl/egctl_test.go
Labels: release/feature-new

#1277 Update version to 0.5.0
  VERSION
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#1279 Update cosign to v2.2.3
  .github/workflows/call-release-image.yaml
Labels: release/bug, release/none

#1280 Fix not mangle policy insertion priority
  pkg/agent/police.go
Labels: release/bug
