Repository spidernet-io/egressgateway, pull requests merged in 2024-01, with the labels that each got.

#1105 E2E: enhance the test cases stability
  test/e2e/common/ds.go
  test/e2e/common/pod.go
  test/e2e/egressendpointslice/egressendpointslice_test.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
  test/e2e/reliability/reliability_ip_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/none, kind/e2e

#1130 Add some ut
  Makefile
  pkg/agent/metrics/metrics_test.go
  pkg/agent/route/route.go
  pkg/agent/route/route_test.go
  pkg/agent/vxlan/parent_test.go
  pkg/agent/vxlan/vxlan_test.go
  pkg/config/config_test.go
  pkg/controller/egress_cluster_info/egress_cluster_info_test.go
  pkg/controller/egress_cluster_info/tools_test.go
  pkg/controller/endpoint/cluster_endpoint_slice_test.go
  pkg/controller/endpoint/endpoint_slice_test.go
  pkg/markallocator/allocator_test.go
Labels: release/none

#1139 Update EgressGateway validation
  pkg/egressgateway/egress_gateway_webhook.go
Labels: release/bug, Ready

#1153 cancel to delete egressEndpointSlice manually in case S00001
  test/e2e/egressendpointslice/egressendpointslice_test.go
Labels: release/none, kind/ci-bug

#1157 Fix: failed to update IP address of egw
  pkg/egressgateway/egress_gateway_webhook.go
Labels: bug, release/none

#1156 fix duplicate gateway ip in some test case
  test/e2e/egressendpointslice/egressendpointslice_test.go
  test/e2e/egressgateway/egressgateway_test.go
  test/e2e/egresspolicy/egresspolicy_test.go
  test/e2e/reliability/reliability_test.go
Labels: release/none, kind/ci-bug

#1171 Update version to v0.4.2
  VERSION
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none

#1173 Add ip number check in R00008
  test/e2e/reliability/reliability_ip_test.go
Labels: release/none

#1186 Fix gomonkey patch in `for range`
  pkg/controller/egress_cluster_info/egress_cluster_info_test.go
Labels: bug, release/none
