Repository spidernet-io/egressgateway, pull requests merged in 2025-02, with the labels that each got.

#1633 Update .golangci.yml to properly configure the skip-dirs field
  .golangci.yaml
Labels: release/none

#1588 Add a detection method to select different VXLAN parent network cards for different machines
  charts/README.md
  charts/values.yaml
  pkg/agent/vxlan.go
  pkg/agent/vxlan/parent.go
  pkg/agent/vxlan/parent_test.go
  pkg/config/config.go
Labels: release/feature-new, kind/feature

#1646 fix: correctly generate an array for egress cluster info with extra cidrs
  charts/templates/egressClusterInfo.yaml
Labels: release/bug

#1637 Bump actions/upload-artifact from 4.4.0 to 4.6.0
  .github/workflows/build-image-base.yaml
  .github/workflows/call-e2e.yaml
  .github/workflows/call-release-changelog.yaml
  .github/workflows/call-release-chart.yaml
  .github/workflows/call-release-image.yaml
  .github/workflows/call-release-pages.yaml
  .github/workflows/helm.yml
  .github/workflows/lint-golang.yaml
  .github/workflows/lint-yaml.yaml
Labels: release/none

#1632 Reduce egress gateway agent event
  pkg/agent/agent.go
  pkg/agent/vxlan.go
  pkg/config/config.go
  pkg/controller/endpoint/endpoint_slice.go
Labels: release/bug

#1647 Update version to v0.6.2
  VERSION
  charts/Chart.yaml
  charts/README.md
  charts/values.yaml
Labels: release/none
